version: '2'
services:
  elasticsearch1:
    build: ./elasticsearch/
    container_name: elasticsearch1
    environment:
      - discovery.type=single-node
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - esnet

  mysql:
      image: mysql:5.7
      container_name: mysql
      environment:
          - MYSQL_ROOT_PASSWORD=root
          - MYSQL_DATABASE=briskly_papers
          - MYSQL_USER=briskly_papers
          - MYSQL_PASSWORD=briskly_papers
      volumes:
        - mysql_data:/var/lib/mysql
      networks:
        - mysqlnet

  nginx:
      build:
        context: ./nginx
      container_name: nginx
      volumes:
        - ./php/src:/var/www
        - ./nginx/web/vhost.conf:/etc/nginx/conf.d/default.conf
      ports:
        - 8085:80
      links:
        - app
        - mysql
        - elasticsearch1
      networks:
        - laravelnet

  app:
      build:
        context: ./php/docker
        dockerfile: app.docker
      container_name: app
      volumes:
        - ./php/src:/var/www
      networks:
        - esnet
        - mysqlnet
        - laravelnet
      depends_on:
        - mysql
        - elasticsearch1
      environment:
        - DB_HOST=mysql
        - DB_DATABASE=briskly_papers
        - DB_USERNAME=briskly_papers
        - DB_PASSWORD=briskly_papers

  react:
    build: ./react/
    container_name: react
    entrypoint: sh /home/node/entrypoint.sh
    working_dir: /home/node
    volumes:
      - ./react/:/home/node
    networks:
      - laravelnet

#  fpm:
#    build: ./socat
#    volumes:
#      - ./socat/socat.sh:/socat.sh
#    command: /socat.sh
#    expose:
#      - 9000
#    networks:
#      - laravelnet

volumes:
  esdata1:
    driver: local
  esdata2:
    driver: local
  mysql_data:

networks:
  esnet:
  mysqlnet:
  laravelnet: